openapi: 3.0.0
info:
  version: 0.5.0
  title: Translation interface API and schema definition
  description: >-
    Any MT system wanted to benchmark the model comparison against the listed
    available models has to implement this API contract
  contact:
    name: ekstep foundation
    email: contact@ekstep.org
paths: {}

components:
  securitySchemes:
      authToken:
        type: apiKey
        description: token issued by authenticating the user
        name: auth-token
        in: header
  
  schemas:

    TranslateResponse:
      type: object
      required:
        - languages
        - sentences
      properties:
        languages:
          type: object
          $ref: 'https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/LanguagePair'
        sentences:
          $ref: '#/components/schemas/Sentences'
  
    TranslateRequest:
      type: object
      required:
        - languages
        - sentences
      properties:
        languages:
          type: object
          $ref: 'https://raw.githubusercontent.com/ULCA-IN/ulca/master/specs/common-schemas.yml#/components/schemas/LanguagePair'
        sentences:
          $ref: '#/components/schemas/Sentences'
  
    Sentences:
      type: array
      description: list of
      items:
        $ref: '#/components/schemas/Sentence'
        minItems: 1
        maxItems: 100
  
    Sentence:
      type: object
      required: 
        - sentenceId
        - source
      properties:
        sentenceId:
          type: string
          description: unique identifier of the sentence, should be generated by the caller for every sentence
        source:
          type: string
          description: actual textual data that needs to be translated.
          minLength: 1
        target:
          type: string
          description: actual textual data that needs to be translated.
          minLength: 1