const constants = {
  APISTATUS: "APISTATUS",
  GET_ERROR_REPORT: "GET_ERROR_REPORT",
  LOGOUT: "LOGOUT",
  /**
   * action for Dataset report
   */
  GET_CONTRIBUTION_LIST: "GET_CONTRIBUTION_LIST",
  CLEAR_USER_EVENT: "CLEAR_USER_EVENT",
  GET_DETAILED_REPORT: "GET_DETAILED_REPORT",

  /**
   * action for Dashboard report
   */
  DASHBOARD_DATASETS: "DASHBOARD_DATASETS",
  DASHBOARD_DATASETS_EXPAND: "DASHBOARD_DATASETS_EXPAND",

  /**
   * action for Search report
   */
  GET_MY_REPORT: "GET_MY_REPORT",
  CLEAR_DETAILED_REPORT: "CLEAR_DETAILED_REPORT",
  /**
   * action for search and download report
   */
  GET_SEARCH_OPTIONS: "GET_SEARCH_OPTIONS",
  PAGE_CHANGE: "PAGE_CHANGE",
  ROW_COUNT_CHANGE: "ROW_COUNT_CHANGE",
  SEARCH_PAGE_NO: "SEARCH_PAGE_NO",
  SEARCH_ROW_COUNT_CHANGE: "SEARCH_ROW_COUNT_CHANGE",
  TABLE_PAGINATION_RESET: "TABLE_PAGINATION_RESET",
  SEARCH_TABLE_PAGINATION_RESET: "SEARCH_TABLE_PAGINATION_RESET",
  CONTRIBUTION_TABLE: "CONTRIBUTION_TABLE",
  CLEAR_FILTER: "CLEAR_FILTER",
  CONTRIBUTION_TABLE_VIEW: "CONTRIBUTION_TABLE_VIEW",

  MODEL_ROW_COUNT_CHANGE: "MODEL_ROW_COUNT_CHANGE",
  MODEL_PAGE_CHANGE: "MODEL_PAGE_CHANGE",
  CLEAR_MODEL_FILTER: "CLEAR_MODEL_FILTER",
  GET_SELECTED_FILTER:"GET_SELECTED_FILTER",
  MODEL_CONTRIBUTION_TABLE: "MODEL_CONTRIBUTION_TABLE",
  MODEL_CONTRIBUTION_TABLE_VIEW: "MODEL_CONTRIBUTION_TABLE_VIEW",
  GET_MODEL_CONTRIBUTION_LIST: "GET_MODEL_CONTRIBUTION_LIST",
  SUBMIT_MODEL: "SUBMIT_MODEL",
  SUBMIT_MODEL_SEARCH: "SUBMIT_MODEL_SEARCH",
  UPDATE_SEARCH_FILTER: "UPDATE_SEARCH_FILTER",
  INITIAL_SEARCH_FILTER: "INITIAL_SEARCH_FILTER",
  GET_SEARCHED_LIST: "GET_SEARCHED_LIST",
  SEARCH_FILTER: "SEARCH_FILTER",
  CLEAR_FILTER_MODEL: "CLEAR_FILTER_MODEL",
  GET_MENU_TYPE: "GET_MENU_TYPE",
  GET_MENU_OPTION: "GET_MENU_OPTION",
  TOGGLE_MODEL_STATUS: "TOGGLE_MODEL_STATUS",

  /**
   * action for model benchmark
   */
  RUN_BENCHMARK: "RUN_BENCHMARK",
  SELECT_DATASET: "SELECT_DATASET",
  SELECT_METRIC: "SELECT_METRIC",
  CLEAR_BENCHMARK: "CLEAR_BENCHMARK",
  SEARCH_BENCHMARK: "SEARCH_BENCHMARK",
  FILTER_BENCHMARK: "FILTER_BENCHMARK",
  CLEAR_FILTER_BENCHMARK: "CLEAR_FILTER_BENCHMARK",

  /**
   * action for Reaymade
   */
  READYMADE_SEARCH_FILTER: "READYMADE_SEARCH_FILTER",
  INITIAL_READYMADE_FILTER: "INITIAL_READYMADE_FILTER",
  READYMADE_DATASET_SEARCH: "READYMADE_DATASET_SEARCH",

  /**
   * action for Benchmarkmodel
   */

  BENCHMARK_MODEL_SEARCH: "BENCHMARK_MODEL_SEARCH",
  UPDATE_BENCHMARK_FILTER: "UPDATE_BENCHMARK_FILTER",
  INITIAL_BENCHMARK_FILTER: "INITIAL_BENCHMARK_FILTER",
  BENCHMARK_TABLE: "BENCHMARK_TABLE",

  GET_BENCHMARK_DETAILS: "GET_BENCHMARK_DETAILS",
  GET_METRIC_DETAILS: "GET_METRIC_DETAILS",
};

export default constants;
