const constants = {
  APISTATUS             : "APISTATUS",
  GET_ERROR_REPORT      : "GET_ERROR_REPORT",

  /**
   * action for Dataset report
   */
  GET_CONTRIBUTION_LIST : "GET_CONTRIBUTION_LIST",
  CLEAR_USER_EVENT      : "CLEAR_USER_EVENT",
  GET_DETAILED_REPORT   : "GET_DETAILED_REPORT",


  /**
   * action for Dashboard report
   */
   DASHBOARD_DATASETS   : "DASHBOARD_DATASETS",
   DASHBOARD_DATASETS_EXPAND  : 'DASHBOARD_DATASETS_EXPAND',


   /**
   * action for Search report
   */
   GET_MY_REPORT        : "GET_MY_REPORT",
   CLEAR_DETAILED_REPORT:"CLEAR_DETAILED_REPORT",
   /**
    * action for search and download report
    */
   GET_SEARCH_OPTIONS :"GET_SEARCH_OPTIONS",
   PAGE_CHANGE :"PAGE_CHANGE",
   ROW_COUNT_CHANGE:"ROW_COUNT_CHANGE",
   SEARCH_PAGE_NO:"SEARCH_PAGE_NO",
   SEARCH_ROW_COUNT_CHANGE:"SEARCH_ROW_COUNT_CHANGE",
   TABLE_PAGINATION_RESET:"TABLE_PAGINATION_RESET",
   SEARCH_TABLE_PAGINATION_RESET:"SEARCH_TABLE_PAGINATION_RESET",
   CONTRIBUTION_TABLE:"CONTRIBUTION_TABLE",
   CLEAR_FILTER :"CLEAR_FILTER"
};

export default constants;
